# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sucg/cour/c++/TP_sucg_lorieaul

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sucg/cour/c++/TP_sucg_lorieaul/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sucg/cour/c++/TP_sucg_lorieaul/build/CMakeFiles /home/sucg/cour/c++/TP_sucg_lorieaul/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sucg/cour/c++/TP_sucg_lorieaul/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simulation

# Build rule for target.
simulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simulation
.PHONY : simulation

# fast build rule for target.
simulation/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/simulation.dir/build.make src/CMakeFiles/simulation.dir/build
.PHONY : simulation/fast

#=============================================================================
# Target rules for targets named halley

# Build rule for target.
halley: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 halley
.PHONY : halley

# fast build rule for target.
halley/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/halley.dir/build.make test/CMakeFiles/halley.dir/build
.PHONY : halley/fast

#=============================================================================
# Target rules for targets named q3tp2

# Build rule for target.
q3tp2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 q3tp2
.PHONY : q3tp2

# fast build rule for target.
q3tp2/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/q3tp2.dir/build.make test/CMakeFiles/q3tp2.dir/build
.PHONY : q3tp2/fast

#=============================================================================
# Target rules for targets named testpoint

# Build rule for target.
testpoint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testpoint
.PHONY : testpoint

# fast build rule for target.
testpoint/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/testpoint.dir/build.make test/CMakeFiles/testpoint.dir/build
.PHONY : testpoint/fast

#=============================================================================
# Target rules for targets named testUnivers

# Build rule for target.
testUnivers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testUnivers
.PHONY : testUnivers

# fast build rule for target.
testUnivers/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/testUnivers.dir/build.make test/CMakeFiles/testUnivers.dir/build
.PHONY : testUnivers/fast

#=============================================================================
# Target rules for targets named q1tp4

# Build rule for target.
q1tp4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 q1tp4
.PHONY : q1tp4

# fast build rule for target.
q1tp4/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/q1tp4.dir/build.make test/CMakeFiles/q1tp4.dir/build
.PHONY : q1tp4/fast

#=============================================================================
# Target rules for targets named testcell

# Build rule for target.
testcell: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testcell
.PHONY : testcell

# fast build rule for target.
testcell/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/testcell.dir/build.make test/CMakeFiles/testcell.dir/build
.PHONY : testcell/fast

#=============================================================================
# Target rules for targets named testuniv

# Build rule for target.
testuniv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testuniv
.PHONY : testuniv

# fast build rule for target.
testuniv/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/testuniv.dir/build.make test/CMakeFiles/testuniv.dir/build
.PHONY : testuniv/fast

#=============================================================================
# Target rules for targets named halley2

# Build rule for target.
halley2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 halley2
.PHONY : halley2

# fast build rule for target.
halley2/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/halley2.dir/build.make test/CMakeFiles/halley2.dir/build
.PHONY : halley2/fast

#=============================================================================
# Target rules for targets named collision

# Build rule for target.
collision: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 collision
.PHONY : collision

# fast build rule for target.
collision/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/collision.dir/build.make test/CMakeFiles/collision.dir/build
.PHONY : collision/fast

#=============================================================================
# Target rules for targets named rebond

# Build rule for target.
rebond: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rebond
.PHONY : rebond

# fast build rule for target.
rebond/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/rebond.dir/build.make test/CMakeFiles/rebond.dir/build
.PHONY : rebond/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... collision"
	@echo "... halley"
	@echo "... halley2"
	@echo "... q1tp4"
	@echo "... q3tp2"
	@echo "... rebond"
	@echo "... simulation"
	@echo "... testUnivers"
	@echo "... testcell"
	@echo "... testpoint"
	@echo "... testuniv"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

